import pandas as pd
import common.DCOreport as DCOreport

# Global variable for the system type
system = "VC"

def color_status(val):
    """
    Standard coloring for OK/Warning/Critical.
    """
    color_map = {
        "OK": DCOreport.PASTEL_GREEN,
        "Warning": DCOreport.PASTEL_YELLOW,
        "Critical": DCOreport.PASTEL_RED
    }
    return color_map.get(val, "")


def color_off_vms(val):
    """
    Red color if there are powered off VMs (val > 0).
    """
    try:
        count = int(val)
        return DCOreport.PASTEL_RED if count > 0 else DCOreport.PASTEL_GREEN
    except:
        return ''

def create_DC(dcocfg, dcorpt):

    """
    Entry point to add the vCenter summary table to the Daily Check report.
    """
    for instance in dcocfg.instances(system):
        # Load the summary dataframe generated by processinfo
        summary_df = DCOreport.csv_to_styleddf(system, instance, "systemSummary", dcocfg)
        
        if not summary_df.data.empty:
            # 1. Apply status coloring to specific status rows
            summary_df = DCOreport.format_by_rowid(summary_df, [
                ("Appliance Health", color_status),
                ("Hosts Connectivity", color_status),
                ("Datastore Capacity", color_status),
                ("Active Alerts", color_status)
            ])
            
            # 2. Apply custom coloring for 'VMs Powered Off' row
            summary_df = DCOreport.format_cells_by_rowid(summary_df, "VMs Powered Off", color_off_vms)
            
            # 3. Apply gray background and bold font to the row headers (First column)
            # This makes the titles of the rows stand out as requested
            # first_col = summary_df.data.columns[0]
            # summary_df = summary_df.set_properties(subset=[first_col], **{
                # 'font-weight': 'bold',
                # 'background-color': '#f2f2f2'
            # })
            
            # 4. Add the table to the 'Compute' section under the title 'vSphere'
            dcorpt.add_table("Compute", "vSphere", instance, "System Summary", summary_df)


if __name__ == "__main__":
    from common.DCOconfig import DCOconfig
    dcocfg = DCOconfig("config_encrypted.json")
    dcorpt = DCOreport.DCOreport("vSphere Daily Check TEST")
    create_DC(dcocfg, dcorpt)
    dcorpt.save_html("test_vc_report.html")
