import pandas as pd
import common.DCOreport as DCOreport

# Global variable for the system type
system = "VC"

def color_status(val):
    """
    Standard coloring for OK/Warning/Critical.
    """
    color_map = {
        "OK": DCOreport.PASTEL_GREEN,
        "Warning": DCOreport.PASTEL_YELLOW,
        "Critical": DCOreport.PASTEL_RED
    }
    return color_map.get(val, "")


def create_DC(dcocfg, dcorpt):
    """
    Entry point to add the vCenter summary table to the Daily Check report.
    """
    for instance in dcocfg.instances(system):
        # Load the summary dataframe generated by processinfo
        df = dcocfg.load_csv_to_dataframe(system, instance, "systemSummary")
        
        if not df.empty:
            # Filter out the "VMs Powered Off" row as requested
            df = df[df.iloc[:, 0] != "VMs Powered Off"]
            
            # Apply base styling
            summary_df = DCOreport.table_base_styler(df)
            
            # 1. Apply status coloring to specific status rows
            summary_df = DCOreport.format_by_rowid(summary_df, [
                ("Appliance Health", color_status),
                ("Hosts Connectivity", color_status),
                ("Datastore Capacity", color_status),
                ("Active Alerts", color_status)
            ])
            
            # 4. Add the table to the 'Compute' section under the title 'vSphere'
            dcorpt.add_table("Compute", "vSphere", instance, "System Summary", summary_df)


if __name__ == "__main__":
    from common.DCOconfig import DCOconfig
    dcocfg = DCOconfig("config_encrypted.json")
    dcorpt = DCOreport.DCOreport("vSphere Daily Check TEST")
    create_DC(dcocfg, dcorpt)
    dcorpt.save_html("test_vc_report.html")
